Readme doc
totvs/tnf-npgsql-migration pull request #1
Opened 2022-09-19 19:07 UTC by jamir-araujo

2022-09-19 19:17 UTC, raphaelpintado commented
Test comment

2022-09-28 18:35 UTC, jonas-medeiros92 requested changes

2022-09-28 18:35 UTC, jonas-medeiros92 commented on Readme.md
> +Lembando, os códigos das migrações, model da migração e ModelSnapshot são gerados especificamente para o provider sendo usando. Por isso não é possível usar migrações geradas com o provider do SqlSer
```suggestion
Lembrando, os códigos das migrações, model da migração e ModelSnapshot são gerados especificamente para o provider sendo usando. Por isso não é possível usar migrações geradas com o provider do SqlServer num provider de PostgreSQL ou Oracle. Da mesma forma, não é possível usar as migrações geradas pelo provider DotConnect no provider da Npgsql, pois cada provider tem customizações e annotations especificas que ele usa ao gerar o script SQL da migração.
```

2022-09-28 18:35 UTC, jonas-medeiros92 commented on Readme.md
> +# Migração do Devart DotConnet for PostgreSql para Npgsql
```suggestion
# Migração de provider para banco de dados PostgreSql: Devart DotConnect para NpgSql
```

2022-09-28 18:35 UTC, jonas-medeiros92 commented on Readme.md
> +Devido a muitos problemas e atrasos enfrentados com o do provider da Devart, chegamos a conclusão que não podemos mais usar e encorajar os times a usar esse provider.
```suggestion
Devido a muitos problemas e atrasos enfrentados com fornecedor Devart, chegamos a conclusão que não iremos mais usar e encorajar os times a usar o provider DotConnect.
```

2022-09-28 18:35 UTC, jonas-medeiros92 commented on Readme.md
> +Agora vamos passar a usar e recomendar o uso do provider de código aberto da Npgsql.
```suggestion
De agora em diante passamos a usar e recomendar o uso do provider de código aberto da Npgsql.
```

2022-09-28 18:35 UTC, jonas-medeiros92 commented on Readme.md
> +Neste repositório temos uma aplicação que vai servir de exemplo de migração, e também será para seguir o tutorial no final desse documento.
```suggestion
Neste repositório disponibilizamos uma aplicação que vai servir de exemplo de migração, e também o tutorial a ser seguido no processo.
```

2022-09-28 18:35 UTC, jonas-medeiros92 commented on Readme.md
> +Vamos entender o que é necessário fazer para migrar do provider da Devart para o da Npgsql.
```suggestion
Vamos entender o que é necessário para migrar do provider Devart para Npgsql.
```

2022-09-28 18:35 UTC, jonas-medeiros92 commented on Readme.md
> +O primeiro passo seria nos registros dos DbContext da aplicação, mudar a chamada de `UsePostgreSql` para um `UseNgpsql`.
```suggestion
O primeiro passo é alterar os registros dos DbContext da aplicação, mudando a chamada de `UsePostgreSql` para `UseNgpsql`.
```

2022-09-28 18:35 UTC, jonas-medeiros92 commented on Readme.md
> +Porém não é tão simples assim. As migrações da sua aplicação são feitas especificamente para o provider de Devart. Isso não seria um problema se as migrações do passado nunca tivesse que ser executad
```suggestion
Porém não é tão simples assim. As migrações da sua aplicação são feitas especificamente para o provider da Devart. Isso não seria um problema se as migrações do passado nunca tivesse que ser executadas novamente, mas isso não é uma verdade.
```

2022-09-28 18:35 UTC, jonas-medeiros92 commented on Readme.md
> +Outro caso e para aplicações multitenant com isolamento por schema. Nessas aplicações toda vez um tenant novo é provisionado, é necessário criar um schema para esse tenant e rodar todas a migrações a
```suggestion
Outro caso é para aplicações multitenant com isolamento por schema. Nessas aplicações toda vez que um tenant novo é provisionado, é necessário criar o schema e rodar todas a migrações apontando para o tenant.
```

2022-09-28 18:35 UTC, jonas-medeiros92 commented on Readme.md
> +Por esse motivos temos a necessidade converter a migrações que forma feita pelo provider da Devart para migrações para o provider da Npgsql.
```suggestion
Por esses motivos temos a necessidade converter as migrações.
```

2022-09-28 18:35 UTC, jonas-medeiros92 commented on Readme.md
> +No exemplo, o aquivo `20220825184314_CreateDatabase.cs` contem o código que é usado para gerar o script SQL de migração, o arquivo `20220825184314_CreateDatabase.Designer.cs` com tem o snapshot com o
```suggestion
No exemplo, o arquivo `20220825184314_CreateDatabase.cs` contém o código que é usado para gerar o script SQL de migração, o arquivo `20220825184314_CreateDatabase.Designer.cs` contém o snapshot com o estado da model no momento que a migração foi criada, e o arquivo `MyDbContextModelSnapshot.cs` contém o snapshot com o último estado da model, ou seja o estado da model quando o a última migration foi adicionada, que nesse caso é a `20220825184314_CreateDatabase`. Se olharmos a definição da model nos arquivos `20220825184314_CreateDatabase.Designer.cs` e `MyDbContextModelSnapshot.cs`, veremos que a definição é a mesma.
```

2022-09-28 18:35 UTC, jonas-medeiros92 commented on Readme.md
> +Ele faz isso comparando o ModelSnapshot, que no nosso exemplo fica no arquivo `MyDbContextModelSnapshot.cs`, com a model construída a partir no DbContext.
```suggestion
Ele faz isso comparando o ModelSnapshot, que no nosso exemplo fica no arquivo `MyDbContextModelSnapshot.cs`, com a model construída a partir do DbContext.
```

2022-09-28 18:35 UTC, jonas-medeiros92 commented on Readme.md
> +Quando executamos o comando `Add-Migration` o EF Core instancia o DbContext em questão e constrói a sua model através do método `OnModelCreating`. Com essa model construída, ele compara ela com a mod
```suggestion
Quando executamos o comando `Add-Migration` o EF Core instância o DbContext em questão e constrói a sua model através do método `OnModelCreating`. Com essa model construída, ele compara com a model do ModelSnapshot, com a diferença ele gera o código da migração e depois atualiza o ModelSnapshot.
```

2022-09-28 18:35 UTC, jonas-medeiros92 commented on Readme.md
> +Ela serve para revert o ModelSnapshot para uma migration anterior.
```suggestion
Ela serve para reverter o ModelSnapshot para uma migration anterior.
```

2022-09-28 18:35 UTC, jonas-medeiros92 commented on Readme.md
> +Exemplo, no nosso caso de exemplo, se executarmos o comando `Remove-Migration`, vamos voltar para esta situação.
```suggestion
Exemplo, no nosso caso, se executarmos o comando `Remove-Migration`, vamos voltar para esta situação.
```

2022-09-28 18:35 UTC, jonas-medeiros92 commented on Readme.md
> +Como não podemos usar as migrações geradas com o provider da Devart e termos que converte-las para migrações compatíveis com o Npgsql, nossa estrategia será regerar as migrações usando o provider da
```suggestion
Como não podemos usar as migrações geradas pelo DotConnect com o novo provider, então temos que convertê-las para migrações compatíveis com o Npgsql. Para isso nossa estratégia será regerar as migrações usando o novo provider.
```

2022-09-28 18:35 UTC, jonas-medeiros92 commented on Readme.md
> +> Mas como fazer isso sem alterar model do DbContext que a aplicação já está usando?
```suggestion
> Mas como fazer isso sem alterar a model do DbContext que a aplicação já está usando?
```

2022-09-28 18:35 UTC, jonas-medeiros92 commented on Readme.md
> +A estrategia envolve o uso dos comandos `Update-Database`, `Scaffold-DbContext` e `Add-Migration`.
```suggestion
A estratégia envolve o uso dos comandos `Update-Database`, `Scaffold-DbContext` e `Add-Migration`.
```

2022-09-28 18:35 UTC, jonas-medeiros92 commented on Readme.md
> +Esse comando vai executar as migrações até a migração `InitialModel`, que no caso é primeira.
```suggestion
Esse comando vai executar as migrações até a migração `InitialModel`, que é a primeira.
```

2022-09-28 18:35 UTC, jonas-medeiros92 commented on Readme.md
> +Ou seja, agora temos um DbContext que representa o estado model apos a primeira migração.
```suggestion
Ou seja, agora temos um DbContext que representa o estado da model após a primeira migração.
```

2022-09-28 18:35 UTC, jonas-medeiros92 commented on Readme.md
> +Agora deixamos o banco de dados estado de modelagem da migração `AddingUserTable`.
```suggestion
Agora deixamos o banco de dados no estado de modelagem da migração `AddingUserTable`.
```

2022-09-28 18:35 UTC, jonas-medeiros92 commented on Readme.md
> +Depois executamos o comando `Scaffold-DbContext` da mesma forma. Agora teremos um DbContext que representa do estado da model apos a migração `AddingUserTable`.
```suggestion
Depois executamos o comando `Scaffold-DbContext` da mesma forma. Agora teremos um DbContext que representa do estado da model após a migração `AddingUserTable`.
```

2022-09-28 18:35 UTC, jonas-medeiros92 commented on Readme.md
> +Claro, esse processo não vai gerar um código que pode ser portado diretamente para o DbContext original da aplicação, pois sempre temos algumas diferenças entre os nomes no bando de dados e os nomes
```suggestion
Contudo, esse processo não vai gerar um código que pode ser portado diretamente para o DbContext original da aplicação, pois sempre temos algumas diferenças entre os nomes no banco de dados e os nomes na model do DbContext, nome de relacionamento, mapeamentos de alguns tipos e etc. Ainda, o processo é bastante trabalhoso de se fazer manualmente e envolve muita repetição, por isso desenvolvemos uma ferramenta e um pacote para auxiliar.
```

2022-09-28 18:35 UTC, jonas-medeiros92 commented on Readme.md
> +`Tnf.EntityFrameworkCore.Migration.Tool` foi desenvolvido com uma ferramente dotnet tool que está disponível no feed do TNF;
```suggestion
`Tnf.EntityFrameworkCore.Migration.Tool` foi desenvolvido como uma ferramenta dotnet tool que está disponível no feed do TNF;
```

2022-09-28 18:35 UTC, jonas-medeiros92 commented on Readme.md
> +Entes de instalar a ferramenta, é necessário instalar a dotnet tool EF Core na versão 3.1.26.
```suggestion
Antes de instalar a ferramenta, é necessário instalar a dotnet tool EF Core na versão 3.1.26.
```

2022-09-28 18:35 UTC, jonas-medeiros92 commented on Readme.md
> +> Note que no final do comando adicionamos o source https://www.myget.org/F/tnf/api/v3/index.json, que é feed do TNF.
```suggestion
> Note que no final do comando adicionamos o source https://www.myget.org/F/tnf/api/v3/index.json, que é o feed do TNF.
```

2022-09-28 18:35 UTC, jonas-medeiros92 commented on Readme.md
> +O `Tnf.EntityFrameworkCore.Migration.Design` deve ser usado no projeto onde ser vai criar os DbContext de migração. E tem as seguintes funções
```suggestion
O `Tnf.EntityFrameworkCore.Migration.Design` deve ser usado no projeto onde serão criados os DbContext de migração. E tem as seguintes funções
```

2022-09-28 18:35 UTC, jonas-medeiros92 commented on Readme.md
> +* Fornece a opção algumas opções que são usadas durante o processo de migração.
```suggestion
* Fornece algumas opções que são usadas durante o processo de migração.
```

2022-09-28 18:35 UTC, jonas-medeiros92 commented on Readme.md
> +Agora vamos fazer exemplo pratico de uso da ferramenta e pacote com uma aplicação.
```suggestion
Agora vamos fazer exemplo prático de uso da ferramenta e do pacote com uma aplicação.
```

2022-09-28 18:35 UTC, jonas-medeiros92 commented on Readme.md
> +> Use a branch `master` desse repositório como ponto de inicio para seguir o tutorial.
```suggestion
> Use a branch `master` desse repositório como ponto de início para seguir o tutorial.
```

2022-09-28 18:35 UTC, jonas-medeiros92 commented on Readme.md
> +    public class BlogPostMetrics
```suggestion
    public class BlogPostMetric
```

2022-09-28 18:35 UTC, jonas-medeiros92 commented on Readme.md
> +    public class AuthorMetrics
```suggestion
    public class AuthorMetric
```

2022-09-28 18:35 UTC, jonas-medeiros92 commented on Readme.md
> +Antes de iniciarmos o processo de migração, vamos gerar script completo de migração com as migrações originais.
```suggestion
Antes de iniciarmos o processo de migração, vamos gerar o script completo de migração com as migrações originais.
```

2022-09-28 18:35 UTC, jonas-medeiros92 commented on Readme.md
> +Vamos guardar esse script para poder comparar com script após a migração para Npgsql.
```suggestion
Vamos guardar esse script para poder comparar com o script após a migração para Npgsql.
```

2022-09-28 18:35 UTC, jonas-medeiros92 commented on Readme.md
> +Agora vamos adicionar um projeto do tipo `Console App` na nossa solution. Como o projeto e EF Core para PostgreSQL da nossa aplicação se chama `BlogManager.EFCore.PostgreSql`, vamos chamar esse novo
```suggestion
Agora vamos adicionar um projeto do tipo `Console App` na nossa solution. Como o projeto EF Core para PostgreSQL da nossa aplicação se chama `BlogManager.EFCore.PostgreSql`, vamos chamar esse novo projeto de `BlogManager.EFCore.PostgreSql.Recover`, e vamos selecionar o Framework .NET Core 3.1 para ele.
```

2022-09-28 18:35 UTC, jonas-medeiros92 commented on Readme.md
> +No projeto `BlogManager.EFCore.PostgreSql.Recover` vamos fazer referencia ao projeto `BlogManager.EFCore.PostgreSql`.
```suggestion
No projeto `BlogManager.EFCore.PostgreSql.Recover` vamos fazer referência ao projeto `BlogManager.EFCore.PostgreSql`.
```

2022-09-28 18:35 UTC, jonas-medeiros92 commented on Readme.md
> +A interface `IDesignTimeServices` implementada pela classe é uma interface definida pelo EF Core, e ela permite registar e substituir services que serão usadas nas operações de design time, tipo `Add
```suggestion
A interface `IDesignTimeServices` implementada por essa classe é uma interface definida pelo EF Core. Ela permite registar e substituir services que serão usadas nas operações de design time, tipo `Add-Migration`, `Update-Database`, `Scaffold-Context` e ect. Já o método de extensão `AddTnfEFCoreProviderMigration` é definido no pacote `Tnf.EntityFrameworkCore.Migration.Design` e faz o registro e substituição de services que precisamos para fazer essa migração. Dentro da lambda desse método também registramos os DbContext da aplicação que vamos migrar. O Registro é necessário porque durante o processo de Scaffold usamos a model do DbContext da aplicação para dar o nome correto as propriedades do DbContext gerado e não apenas no nome da coluna, como originalmente é feito.
```

2022-09-28 18:35 UTC, jonas-medeiros92 commented on Readme.md
> +O primeiro parâmetro do método `AddTnfEFCoreProviderMigration` é a string de conexão do banco de dados que vamos usar para regerar as migrações. No exemplo estamos apontando para o banco `BlogManager
```suggestion
O primeiro parâmetro do método `AddTnfEFCoreProviderMigration` é a string de conexão do banco de dados que vamos usar para regerar as migrações. No exemplo estamos apontando para o banco `BlogManager_Recover`, então vamos criar um banco de dados com esse nome no PostgreSql local. Não precisamos fazer nada, além de criar o banco de dados com esse nome.
```

2022-09-28 18:35 UTC, jonas-medeiros92 commented on Readme.md
> +Agora vamos criar uma pasta chamada `Properties` Adicionar um arquivo `AssemblyInfo.cs`.
```suggestion
Agora vamos criar uma pasta chamada `Properties` e adicionar um arquivo `AssemblyInfo.cs`.
```

2022-09-28 18:35 UTC, jonas-medeiros92 commented on Readme.md
> +Dentro do arquivo vamos por o seguinte conteúdo:
```suggestion
Dentro do arquivo vamos pôr o seguinte conteúdo:
```

2022-09-28 18:35 UTC, jonas-medeiros92 commented on Readme.md
> +Já estamos quase prontos para rodar a ferramenta. Primeiro precisamos ajustar a factory do nosso `PostgreSqlBlogDbContext`.
```suggestion
Já estamos quase prontos para rodar a ferramenta. Agora precisamos ajustar a factory do nosso `PostgreSqlBlogDbContext`.
```

2022-09-28 18:35 UTC, jonas-medeiros92 commented on Readme.md
> +Agora vamos rodar a ferramenta. Mas primeiro temos que instala-la.
```suggestion
Agora vamos rodar a ferramenta. Basta instalá-la.
```

2022-09-28 18:35 UTC, jonas-medeiros92 commented on Readme.md
> +Vamos instalar do ferramenta dotnet-ef primeiro com o comando `dotnet tool install dotnet-ef -g --version 3.1.26` em uma janela de cmd.
```suggestion
Vamos instalar do ferramenta dotnet-ef com o comando `dotnet tool install dotnet-ef -g --version 3.1.26` em uma janela de cmd.
```

2022-09-28 18:35 UTC, jonas-medeiros92 commented on Readme.md
> +* `--context-project`: O projeto que o DbContext se encontra;
```suggestion
* `--context-project`: O projeto em que o DbContext se encontra;
```

2022-09-28 18:35 UTC, jonas-medeiros92 commented on Readme.md
> +* `--context-assembly`: O assembly que o DbContext se encontra. Nesse caso apontamos para o assembly dentro da pasta `bin` do projeto `BlogManager.EFCore.PostgreSql.Recover`, já que as operações serã
```suggestion
* `--context-assembly`: O assembly em que o DbContext se encontra. Nesse caso apontamos para o assembly dentro da pasta `bin` do projeto `BlogManager.EFCore.PostgreSql.Recover`, já que as operações serão feitas nesse diretório;
```

2022-09-28 18:35 UTC, jonas-medeiros92 commented on Readme.md
> +Também temos uma entidade que não estava na model original. A entidade `BlogRatings` existia na model original em versões anteriores, mas a ultima migração removeu ela. Como a ferramenta apensa sobre
```suggestion
Também temos uma entidade que não estava na model original. A entidade `BlogRatings` existia na model original em versões anteriores, mas foi removida na última migração. Como a ferramenta apenas sobrescreve o conteúdo da pasta `Scaffold_PostgreSqlBlogDbContext` sem apagar nada, a entidade permanece na pasta. Porém se formos olhar dentro da classe `ProviderMigration_PostgreSqlBlogDbContext`, ela não vai estar lá.
```

2022-09-28 18:35 UTC, jonas-medeiros92 commented on Readme.md
> +Dá para notar também que esse novo DbContext não está no mesmo namespace que o DbContext original, ele está no namespace `ProviderMigration.BlogManager.EFCore.PostgreSql`. Não é só o DbContext, as en
```suggestion
Nota-se que o novo DbContext não está no mesmo namespace que o DbContext original, ele está no namespace `ProviderMigration.BlogManager.EFCore.PostgreSql`. Não é só o DbContext, as entidades da model também foram colocadas no mesmo namespace. Isso é feito para evitar conflito com as classes do modelo original.
```

2022-09-28 18:35 UTC, jonas-medeiros92 commented on Readme.md
> +Agora que temos o novo DbContext, o nosso objectivo não é substituir o DbContext da nossa aplicação por ele, mas sim usar partes dele ajustar o DbContext original o poder rodar as migrações com o pro
```suggestion
Agora temos o novo DbContext. Nosso objetivo não é substituir o DbContext da nossa aplicação por ele, mas sim usar partes dele para ajustar o DbContext original e poder rodar as migrações com o provider da Npgsql.
```

2022-09-28 18:35 UTC, jonas-medeiros92 commented on Readme.md
> +Vamos começão copiando o conteúdo do método `OnModelCreating`. Mas não vamos copiar para o `OnModelCreating` do `BlogDbContext`, vamos copiar para o `OnModelCreating` do `PostgreSqlBlogDbContext`, po
```suggestion
Vamos começar copiando o conteúdo do método `OnModelCreating`. Mas não vamos copiar para o `OnModelCreating` do `BlogDbContext`, vamos copiar para o `OnModelCreating` do `PostgreSqlBlogDbContext`, pois esse é o DbContext especifico para PostgreSql.
```

2022-09-28 18:35 UTC, jonas-medeiros92 commented on Readme.md
> +Após a copia vamos ter alguns erros de compilação porque o mapeamento das relações entre as entidades está diferente, pois no modelo original não temos a navegação bidirecional. Nesse caso basta apag
```suggestion
Após a copia vamos ter alguns erros de compilação porque o mapeamento das relações entre as entidades está diferente, pois no modelo original não temos a navegação bidirecional. Nesse caso basta apagar os mapeamentos que estão com erro, pois eles já são registrados no `OnModelCreating` do `BlogDbContext`.
```

2022-09-28 18:35 UTC, jonas-medeiros92 commented on Readme.md
> +Agora vamos olhar dentro da pasta `Migrations` do novo DbContext. Vamos olhar o arquivo `ProviderMigration_PostgreSqlBlogDbContextModelSnapshot.cs`. Esse é o ModelSnapshot do `ProviderMigration_Postg
```suggestion
Agora vamos olhar dentro da pasta `Migrations` do novo DbContext, o arquivo `ProviderMigration_PostgreSqlBlogDbContextModelSnapshot.cs`. Esse é o ModelSnapshot do `ProviderMigration_PostgreSqlBlogDbContext`. Ele também está em um namespace diferente. Então não podemos substituir o arquivo inteiro, ao invés, vamos apenas copiar os conteúdo do método `BuildModel` e substituir pelo conteúdo desse mesmo método no arquivo `PostgreSqlBlogDbContextModelSnapshot.cs`.
```

2022-09-28 18:35 UTC, jonas-medeiros92 commented on Readme.md
> +Agora falta migrar a migrações em si.
```suggestion
Agora falta migrar as migrações em si.
```

2022-09-28 18:35 UTC, jonas-medeiros92 commented on Readme.md
> +Agora já podemos mudar o drive no resto da aplicação.
```suggestion
Agora já podemos mudar o provider no resto da aplicação.
```

2022-09-28 18:35 UTC, jonas-medeiros92 commented on Readme.md
> +Também precisamos remove a chamada para ativação do drive da Devart na classe `Startup`.
```suggestion
Também precisamos remover a chamada para ativação do provider da Devart na classe `Startup`.
```

2022-09-28 18:35 UTC, jonas-medeiros92 commented on Readme.md
> +Pronto!! Aplicação migrada para o Ngpsql para EntityFramework Core.
```suggestion
Pronto!! Aplicação migrada para utilizar o provider NpgSql.
```

2022-09-28 18:35 UTC, jonas-medeiros92 commented on Readme.md
> +Se você quiser ver a nossa versão da aplicação migrada para compara com a sua, olhe a branch `Completed`.
```suggestion
Se você quiser ver a nossa versão da aplicação migrada para comparar com a sua, verifique a branch `Completed`.
```

2022-09-28 18:35 UTC, jonas-medeiros92 commented on Readme.md
> +Caso você tenha uma sua model navigation properties com nomes diferentes das tabelas, a model gerada pela ferramenta vai gerar essas navigations com os nomes das tabelas. Então ao copiar o conteúdo d
```suggestion
Caso você tenha em sua model navigation properties com nomes diferentes das tabelas, a model gerada pela ferramenta vai gerar essas navigations com os nomes das tabelas. Então ao copiar o conteúdo do `OnModelCreating` do DbContext gerado pela ferramenta para o DbContext da aplicação, podem ocorrer alguns erros no mapeamento das navigations. Para resolver basta ajustar os nomes ou remover os mapeamentos duplicados ou que não são necessários.
```

2022-09-28 18:35 UTC, jonas-medeiros92 commented on Readme.md
> +Como vimos durante tutorial, ao fazer a engenharia reversa do banco de dados para gerar o DbContext, algumas coisas vão ficar duplicadas. Os valores padrões das colunas são uma delas, porém, nesse ca
```suggestion
Como vimos durante o tutorial, ao fazer a engenharia reversa do banco de dados para gerar o DbContext, algumas coisas vão ficar duplicadas. Os valores padrões das colunas são uma delas, porém, nesse caso, isso gera erro no EF Core, pois ao restaurar o DbContext vem com o valor padrão como `DefaultValueSql`, que é diferente do que normalmente fazemos nas nossas models.
```

2022-09-28 18:35 UTC, jonas-medeiros92 commented on Readme.md
> +Em boa parte dos caso o valor padrão vai precisar de um ajuste como fizemos no tutorial.
```suggestion
Em boa parte dos casos o valor padrão vai precisar de um ajuste como fizemos no tutorial.
```

2022-09-28 18:35 UTC, jonas-medeiros92 commented on Readme.md
> +Os indices das tabelas vão aparecer na model do DbContext gerado pela ferramenta. Esses indices vão ter nomes. Não esqueça de trazes esse indices para model do DbContext da aplicação.
```suggestion
Os índices das tabelas vão aparecer na model do DbContext gerado pela ferramenta. Esses índices vão ter nomes. Não esqueça de trazer esses índices para a model do DbContext da aplicação.
```

2022-09-28 18:35 UTC, jonas-medeiros92 commented on Readme.md
> +Se sua aplicação teve tabelas ou colunas renomeada, o processo executado pela ferramenta não consegue identificar isso. Por exemplo, se a tabela `BlogPostMetrics` for renomeada para `PostMetrics`, a
```suggestion
Se sua aplicação teve tabelas ou colunas renomeadas, o processo executado pela ferramenta não consegue identificar isso. Por exemplo, se a tabela `BlogPostMetrics` for renomeada para `PostMetrics`, a ferramenta vai criar um comando `drop table` para `BlogPostMetrics` e um `create table` para `PostMetrics`.
```

2022-09-28 18:35 UTC, jonas-medeiros92 commented on Readme.md
> +Um maneira fácil de resolver é criar um banco de dados temporário para cada DbContext.
```suggestion
Logo, aconselhamos criar um banco de dados temporário para cada DbContext.
```

2022-09-28 18:35 UTC, jonas-medeiros92 commented on Readme.md
> +Também é possível resolver passando os nomes das tabelas que pertencem ao DbContext, basta passar o parâmetro `--scaffold-table` uma vez para cada tabela. Ou, Passar via código na hora que está confi
```suggestion
Ou então passar os nomes das tabelas que pertencem ao DbContext. Basta passar o parâmetro `--scaffold-table` uma vez para cada tabela. Ou, passar via código na hora que está configurando o DbContext na chamada `ConfigureTnfDbContext`.
```

2022-09-29 19:23 UTC, byelmendes requested changes

2022-09-29 19:23 UTC, byelmendes commented on Readme.md
> +Lembrando, os códigos das migrações, model da migração e ModelSnapshot são gerados especificamente para o provider sendo usando. Por isso não é possível usar migrações geradas com o provider do SqlSe
```suggestion
Lembrando, os códigos das migrações, model da migração e ModelSnapshot são gerados especificamente para o provider que está sendo usando. Por isso não é possível usar migrações geradas com o provider do SqlServer num provider de PostgreSQL ou Oracle. Da mesma forma, não é possível usar as migrações geradas pelo provider DotConnect no provider da Npgsql, pois cada provider tem customizações e annotations especificas que ele usa ao gerar o script SQL da migração.
```

2022-09-29 19:23 UTC, byelmendes commented on Readme.md
> +Depois executamos o comando `Scaffold-DbContext` da mesma forma. Agora teremos um DbContext que representa do estado da model após a migração `AddingUserTable`.
```suggestion
Depois executamos o comando `Scaffold-DbContext` da mesma forma. Agora teremos um DbContext que representa o estado da model após a migração `AddingUserTable`.
```

2022-09-29 19:23 UTC, byelmendes commented on Readme.md
> +Veremos mais detalhes do uso tando da ferramenta quando do pacote no tutorial a seguir.
```suggestion
Veremos mais detalhes do uso tanto da ferramenta quando do pacote no tutorial a seguir.
```

2022-09-29 19:23 UTC, byelmendes commented on Readme.md
> +A interface `IDesignTimeServices` implementada por essa classe é uma interface definida pelo EF Core. Ela permite registar e substituir services que serão usadas nas operações de design time, tipo `A
```suggestion
A interface `IDesignTimeServices` implementada por essa classe é uma interface definida pelo EF Core. Ela permite registar e substituir services que serão usadas nas operações de design time, tipo `Add-Migration`, `Update-Database`, `Scaffold-Context` e etc. Já o método de extensão `AddTnfEFCoreProviderMigration` é definido no pacote `Tnf.EntityFrameworkCore.Migration.Design` e faz o registro e substituição de services que precisamos para fazer essa migração. Dentro da lambda desse método também registramos os DbContext da aplicação que vamos migrar. O Registro é necessário porque durante o processo de Scaffold usamos a model do DbContext da aplicação para dar o nome correto as propriedades do DbContext gerado e não apenas no nome da coluna, como originalmente é feito.
```

2022-09-29 19:23 UTC, byelmendes commented on Readme.md
> +Após a copia vamos ter alguns erros de compilação porque o mapeamento das relações entre as entidades está diferente, pois no modelo original não temos a navegação bidirecional. Nesse caso basta apag
```suggestion
Após a cópia vamos ter alguns erros de compilação porque o mapeamento das relações entre as entidades está diferente, pois no modelo original não temos a navegação bidirecional. Nesse caso basta apagar os mapeamentos que estão com erro, pois eles já são registrados no `OnModelCreating` do `BlogDbContext`.
```

2022-09-30 20:01 UTC, raphaelpintado requested changes

2022-09-30 20:01 UTC, raphaelpintado commented on Readme.md
> +Primeiro criamos um banco de dados temporário. Depois configuramos o DbContext que queremos regerar a migrações para se conectar nesse banco de dados.
```suggestion
Primeiro criamos um banco de dados temporário. Depois configuramos o DbContext que queremos regerar as migrações para se conectar nesse banco de dados.
```

2022-09-30 20:01 UTC, raphaelpintado commented on Readme.md
> +Quando executamos o comando `Add-Migration` o EF Core instância o DbContext em questão e constrói a sua model através do método `OnModelCreating`. Com essa model construída, ele compara com a model d
```suggestion
Quando executamos o comando `Add-Migration` o EF Core instancia o DbContext em questão e constrói a sua model através do método `OnModelCreating`. Com essa model construída, ele compara com a model do ModelSnapshot, com a diferença ele gera o código da migração e depois atualiza o ModelSnapshot.
```

2022-09-30 20:01 UTC, raphaelpintado commented on Readme.md
> +Porém não é tão simples assim. As migrações da sua aplicação são feitas especificamente para o provider da Devart. Isso não seria um problema se as migrações do passado nunca tivesse que ser executad
```suggestion
Porém não é tão simples assim. As migrações da sua aplicação são feitas especificamente para o provider da Devart. Isso não seria um problema se as migrações do passado nunca tivessem que ser executadas novamente, mas isso não é uma verdade.
```

2022-09-30 20:01 UTC, raphaelpintado commented on Readme.md
> +Contudo, esse processo não vai gerar um código que pode ser portado diretamente para o DbContext original da aplicação, pois sempre temos algumas diferenças entre os nomes no banco de dados e os nome
```suggestion
Contudo, esse processo não vai gerar um código que pode ser portado diretamente para o DbContext original da aplicação, pois sempre temos algumas diferenças entre os nomes no banco de dados e os nomes na model do DbContext, nome de relacionamentos, mapeamentos de alguns tipos e etc. Este processo seria bastante trabalhoso de se fazer manualmente e envolveria muita repetição, por isso desenvolvemos uma ferramenta e um pacote para auxilia-los.
```

2022-09-30 20:01 UTC, raphaelpintado commented on Readme.md
> +* Ajuda no mapeamento dos nomes de campos e tabela que estão no banco de dados, para os os nomes na model do DbContext;
```suggestion
* Ajuda no mapeamento dos nomes de campos e tabelas que estão no banco de dados, para os os nomes na model do DbContext;
```

2022-09-30 20:01 UTC, raphaelpintado commented on Readme.md
> +* Ajuda no mapeamento de alguns tipos de dados no banco dados que acabam vindo diferente da model original;
```suggestion
* Ajuda no mapeamento de alguns tipos de dados no banco dados que acabam vindo diferentes da model original;
```

2022-09-30 20:01 UTC, raphaelpintado commented on Readme.md
> +Veremos mais detalhes do uso tanto da ferramenta quando do pacote no tutorial a seguir.
```suggestion
Veremos mais detalhes do uso tanto da ferramenta quanto do pacote no tutorial a seguir.
```

2022-09-30 20:01 UTC, raphaelpintado commented on Readme.md
> +A interface `IDesignTimeServices` implementada por essa classe é uma interface definida pelo EF Core. Ela permite registar e substituir services que serão usadas nas operações de design time, tipo `A
```suggestion
A interface `IDesignTimeServices` implementada por essa classe é uma interface definida pelo EF Core. Ela permite registrar e substituir services que serão usadas nas operações de design time, tipo `Add-Migration`, `Update-Database`, `Scaffold-Context` e etc. Já o método de extensão `AddTnfEFCoreProviderMigration` é definido no pacote `Tnf.EntityFrameworkCore.Migration.Design` e faz o registro e substituição de services que precisamos para fazer essa migração. Dentro da lambda desse método também registramos os DbContext da aplicação que vamos migrar. O Registro é necessário porque durante o processo de Scaffold usamos a model do DbContext da aplicação para dar o nome correto às propriedades do DbContext gerados e não apenas no nome da coluna, como originalmente é feito.
```

2022-09-30 20:01 UTC, raphaelpintado commented on Readme.md
> +Agora vamos olhar dentro da pasta `Migrations` do novo DbContext, o arquivo `ProviderMigration_PostgreSqlBlogDbContextModelSnapshot.cs`. Esse é o ModelSnapshot do `ProviderMigration_PostgreSqlBlogDbC
```suggestion
Agora vamos olhar dentro da pasta `Migrations` do novo DbContext, o arquivo `ProviderMigration_PostgreSqlBlogDbContextModelSnapshot.cs`. Esse é o ModelSnapshot do `ProviderMigration_PostgreSqlBlogDbContext`. Ele também está em um namespace diferente. Então não podemos substituir o arquivo inteiro, ao invés disso, vamos apenas copiar os conteúdo do método `BuildModel` e substituir pelo conteúdo desse mesmo método no arquivo `PostgreSqlBlogDbContextModelSnapshot.cs`.
```

2022-09-30 20:01 UTC, raphaelpintado commented on Readme.md
> +Agora vamos ajusta a classe `PostgreSqlBlogDbContextFactory`:
```suggestion
Agora vamos ajustar a classe `PostgreSqlBlogDbContextFactory`:
```

2022-10-21 21:49 UTC, merged